const { Sequelize } = require("sequelize");
const fs = require("fs");
if (fs.existsSync("config.env"))
  require("dotenv").config({ path: "./config.env" });

const toBool = (x) => x == "true";

DATABASE_URL = process.env.DATABASE_URL || "./lib/database.db";
let HANDLER = "false";

module.exports = {
  //For Enabling Commands Like AUTO_STATUS_RED Type true For Disenabling Type false
  ANTILINK: toBool(process.env.ANTI_LINK) || false,
  //_________________________________________________________________________________________________________________________________
  ANTILINK_ACTION: process.env.ANTI_LINK || "kick",
  //_________________________________________________________________________________________________________________________________
  AUTO_REACT: process.env.AUTO_REACT || 'false',
  //_________________________________________________________________________________________________________________________________
  AUTO_STATUS_READ: process.env.AUTO_STATUS_READ || 'false',
  //_________________________________________________________________________________________________________________________________
  AUTO_BIO: process.env.AUTO_BIO || 'false',
  //_________________________________________________________________________________________________________________________________
  AUTO_READ_MSG: process.env.AUTO_READ_MSG || 'false',
  //_________________________________________________________________________________________________________________________________
  AUDIO_DATA: process.env.AUDIO_DATA || "Phoenix-MD;Abhishek Suresh;https://graph.org/file/8976892f2f615077b48cd.jpg",
  //_________________________________________________________________________________________________________________________________
  BRANCH: "main",
  //_________________________________________________________________________________________________________________________________
  SESSION_ID: process.env.SESSION_ID || "SUHAIL_07_22_07_23_ewogICJjcmVkcy5qc29uIjogIntcbiAgXCJub2lzZUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMjAwLFxuICAgICAgICAxNDIsXG4gICAgICAgIDIzLFxuICAgICAgICAxMTMsXG4gICAgICAgIDE0MixcbiAgICAgICAgMjQxLFxuICAgICAgICAxMTIsXG4gICAgICAgIDE3NyxcbiAgICAgICAgMTI4LFxuICAgICAgICAxMTEsXG4gICAgICAgIDE3MSxcbiAgICAgICAgNjcsXG4gICAgICAgIDE0NyxcbiAgICAgICAgMjIwLFxuICAgICAgICAxNTIsXG4gICAgICAgIDc1LFxuICAgICAgICAxMDEsXG4gICAgICAgIDIyOSxcbiAgICAgICAgNzgsXG4gICAgICAgIDEyLFxuICAgICAgICAxODAsXG4gICAgICAgIDk4LFxuICAgICAgICAxNzAsXG4gICAgICAgIDI1MCxcbiAgICAgICAgMjM3LFxuICAgICAgICAxNjQsXG4gICAgICAgIDEzNyxcbiAgICAgICAgOTAsXG4gICAgICAgIDIwNSxcbiAgICAgICAgOTAsXG4gICAgICAgIDQxLFxuICAgICAgICA3OVxuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICA2NCxcbiAgICAgICAgODEsXG4gICAgICAgIDM3LFxuICAgICAgICAxOTUsXG4gICAgICAgIDQ1LFxuICAgICAgICAyMTcsXG4gICAgICAgIDIyNCxcbiAgICAgICAgMTI3LFxuICAgICAgICA5MixcbiAgICAgICAgMjAwLFxuICAgICAgICAxNyxcbiAgICAgICAgMTEwLFxuICAgICAgICAxMjcsXG4gICAgICAgIDQ4LFxuICAgICAgICA3MCxcbiAgICAgICAgMjgsXG4gICAgICAgIDE0OCxcbiAgICAgICAgMTI1LFxuICAgICAgICAyMTksXG4gICAgICAgIDEwNyxcbiAgICAgICAgNzEsXG4gICAgICAgIDEzNCxcbiAgICAgICAgMjI4LFxuICAgICAgICA4MCxcbiAgICAgICAgNSxcbiAgICAgICAgNjgsXG4gICAgICAgIDEyMCxcbiAgICAgICAgMTczLFxuICAgICAgICAxMjcsXG4gICAgICAgIDc0LFxuICAgICAgICAxOTMsXG4gICAgICAgIDgwXG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyXCI6IHtcbiAgICBcInByaXZhdGVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAxMTIsXG4gICAgICAgIDE0MyxcbiAgICAgICAgOTEsXG4gICAgICAgIDI0LFxuICAgICAgICA1MixcbiAgICAgICAgMTM1LFxuICAgICAgICAxMDAsXG4gICAgICAgIDI0OCxcbiAgICAgICAgODcsXG4gICAgICAgIDE0MixcbiAgICAgICAgMjMwLFxuICAgICAgICA1MixcbiAgICAgICAgMjA2LFxuICAgICAgICAyMixcbiAgICAgICAgMjM0LFxuICAgICAgICA4LFxuICAgICAgICAyMDMsXG4gICAgICAgIDYsXG4gICAgICAgIDE3NCxcbiAgICAgICAgMTQ2LFxuICAgICAgICA1LFxuICAgICAgICAxNjIsXG4gICAgICAgIDE5MixcbiAgICAgICAgNDMsXG4gICAgICAgIDMzLFxuICAgICAgICA4OSxcbiAgICAgICAgOTEsXG4gICAgICAgIDE0OSxcbiAgICAgICAgMjU1LFxuICAgICAgICAyMzUsXG4gICAgICAgIDI1MCxcbiAgICAgICAgOTZcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMjAxLFxuICAgICAgICAxNTAsXG4gICAgICAgIDU2LFxuICAgICAgICAxNDYsXG4gICAgICAgIDczLFxuICAgICAgICA2LFxuICAgICAgICAyNDEsXG4gICAgICAgIDE4NSxcbiAgICAgICAgMTUsXG4gICAgICAgIDIzMixcbiAgICAgICAgMjI3LFxuICAgICAgICAzOSxcbiAgICAgICAgMjA2LFxuICAgICAgICA5NixcbiAgICAgICAgMjM4LFxuICAgICAgICAyMTQsXG4gICAgICAgIDE2MixcbiAgICAgICAgMTcyLFxuICAgICAgICAxNDMsXG4gICAgICAgIDE5NSxcbiAgICAgICAgNjQsXG4gICAgICAgIDQ1LFxuICAgICAgICAyMixcbiAgICAgICAgNjEsXG4gICAgICAgIDE0NixcbiAgICAgICAgMTUxLFxuICAgICAgICAyNDQsXG4gICAgICAgIDIxMyxcbiAgICAgICAgMTM5LFxuICAgICAgICAxMzYsXG4gICAgICAgIDEzNixcbiAgICAgICAgNTdcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwic2lnbmVkSWRlbnRpdHlLZXlcIjoge1xuICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDU2LFxuICAgICAgICAyMDAsXG4gICAgICAgIDgwLFxuICAgICAgICAxNDQsXG4gICAgICAgIDE1NSxcbiAgICAgICAgMjI0LFxuICAgICAgICAzLFxuICAgICAgICAxNzEsXG4gICAgICAgIDEyLFxuICAgICAgICAxNyxcbiAgICAgICAgMTA0LFxuICAgICAgICAyNDgsXG4gICAgICAgIDE1NyxcbiAgICAgICAgMjI0LFxuICAgICAgICAyNDYsXG4gICAgICAgIDIyLFxuICAgICAgICAyMTksXG4gICAgICAgIDEyOSxcbiAgICAgICAgNDgsXG4gICAgICAgIDY0LFxuICAgICAgICA1NyxcbiAgICAgICAgNCxcbiAgICAgICAgMTkyLFxuICAgICAgICAyNDUsXG4gICAgICAgIDM4LFxuICAgICAgICA0MSxcbiAgICAgICAgMTM3LFxuICAgICAgICAxNDUsXG4gICAgICAgIDE4MCxcbiAgICAgICAgMyxcbiAgICAgICAgMTYzLFxuICAgICAgICA3NlxuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICA5MixcbiAgICAgICAgNTAsXG4gICAgICAgIDIxMSxcbiAgICAgICAgMjQwLFxuICAgICAgICAxOTYsXG4gICAgICAgIDMxLFxuICAgICAgICAyMDIsXG4gICAgICAgIDIwOCxcbiAgICAgICAgMjEzLFxuICAgICAgICA1MixcbiAgICAgICAgMTc2LFxuICAgICAgICAxNjgsXG4gICAgICAgIDE0NCxcbiAgICAgICAgMTE3LFxuICAgICAgICAxNTUsXG4gICAgICAgIDIwNSxcbiAgICAgICAgMTczLFxuICAgICAgICAxNzIsXG4gICAgICAgIDIwMSxcbiAgICAgICAgNTgsXG4gICAgICAgIDE1NSxcbiAgICAgICAgMSxcbiAgICAgICAgMTUsXG4gICAgICAgIDEwMSxcbiAgICAgICAgMTQ5LFxuICAgICAgICAxMzksXG4gICAgICAgIDE3NSxcbiAgICAgICAgMTE1LFxuICAgICAgICAxNDAsXG4gICAgICAgIDE5MCxcbiAgICAgICAgMTU3LFxuICAgICAgICA3M1xuICAgICAgXVxuICAgIH1cbiAgfSxcbiAgXCJzaWduZWRQcmVLZXlcIjoge1xuICAgIFwia2V5UGFpclwiOiB7XG4gICAgICBcInByaXZhdGVcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICA0OCxcbiAgICAgICAgICA4MixcbiAgICAgICAgICAyMTUsXG4gICAgICAgICAgMTgzLFxuICAgICAgICAgIDIxMSxcbiAgICAgICAgICAxNjUsXG4gICAgICAgICAgMTQwLFxuICAgICAgICAgIDEwNyxcbiAgICAgICAgICA1MSxcbiAgICAgICAgICA3MixcbiAgICAgICAgICAxODAsXG4gICAgICAgICAgNTMsXG4gICAgICAgICAgNixcbiAgICAgICAgICAyNTIsXG4gICAgICAgICAgNTEsXG4gICAgICAgICAgMTgwLFxuICAgICAgICAgIDIzMCxcbiAgICAgICAgICAxNyxcbiAgICAgICAgICAxOTQsXG4gICAgICAgICAgMjU0LFxuICAgICAgICAgIDExNixcbiAgICAgICAgICA2NyxcbiAgICAgICAgICAxMDQsXG4gICAgICAgICAgMjQ0LFxuICAgICAgICAgIDIwNixcbiAgICAgICAgICAyMzEsXG4gICAgICAgICAgOTUsXG4gICAgICAgICAgMTYxLFxuICAgICAgICAgIDIwMyxcbiAgICAgICAgICAxMjUsXG4gICAgICAgICAgMjQsXG4gICAgICAgICAgNjVcbiAgICAgICAgXVxuICAgICAgfSxcbiAgICAgIFwicHVibGljXCI6IHtcbiAgICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgICAgMTY5LFxuICAgICAgICAgIDEyOSxcbiAgICAgICAgICA2LFxuICAgICAgICAgIDIxOSxcbiAgICAgICAgICAxNDcsXG4gICAgICAgICAgMjAyLFxuICAgICAgICAgIDE3OSxcbiAgICAgICAgICAyMjQsXG4gICAgICAgICAgMTg1LFxuICAgICAgICAgIDI5LFxuICAgICAgICAgIDEyOCxcbiAgICAgICAgICAzNyxcbiAgICAgICAgICA4OCxcbiAgICAgICAgICA2OCxcbiAgICAgICAgICAyMzQsXG4gICAgICAgICAgMTAxLFxuICAgICAgICAgIDEzMCxcbiAgICAgICAgICAyMyxcbiAgICAgICAgICAyMDIsXG4gICAgICAgICAgNzMsXG4gICAgICAgICAgMjUsXG4gICAgICAgICAgMzIsXG4gICAgICAgICAgMTM1LFxuICAgICAgICAgIDM4LFxuICAgICAgICAgIDgzLFxuICAgICAgICAgIDEzLFxuICAgICAgICAgIDE0NSxcbiAgICAgICAgICAxMDIsXG4gICAgICAgICAgMjA4LFxuICAgICAgICAgIDE5NixcbiAgICAgICAgICAxMjAsXG4gICAgICAgICAgMTRcbiAgICAgICAgXVxuICAgICAgfVxuICAgIH0sXG4gICAgXCJzaWduYXR1cmVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAyMzQsXG4gICAgICAgIDE4NixcbiAgICAgICAgMjUsXG4gICAgICAgIDI0NCxcbiAgICAgICAgMjcsXG4gICAgICAgIDQ2LFxuICAgICAgICAyMzUsXG4gICAgICAgIDIxLFxuICAgICAgICAyMzYsXG4gICAgICAgIDIxOCxcbiAgICAgICAgMTA2LFxuICAgICAgICAyMjksXG4gICAgICAgIDE1NSxcbiAgICAgICAgMTcwLFxuICAgICAgICAyNTUsXG4gICAgICAgIDIwMCxcbiAgICAgICAgMjIxLFxuICAgICAgICAyNDEsXG4gICAgICAgIDE0NixcbiAgICAgICAgMjI2LFxuICAgICAgICA3NSxcbiAgICAgICAgNzgsXG4gICAgICAgIDY4LFxuICAgICAgICAxMjAsXG4gICAgICAgIDcyLFxuICAgICAgICA2MCxcbiAgICAgICAgMjA5LFxuICAgICAgICA0OSxcbiAgICAgICAgMTQwLFxuICAgICAgICAxMjcsXG4gICAgICAgIDY2LFxuICAgICAgICAyMTQsXG4gICAgICAgIDE4MSxcbiAgICAgICAgMjQsXG4gICAgICAgIDE0MSxcbiAgICAgICAgMyxcbiAgICAgICAgMTE4LFxuICAgICAgICAyNyxcbiAgICAgICAgMTQ1LFxuICAgICAgICAxNTEsXG4gICAgICAgIDM3LFxuICAgICAgICAyMzYsXG4gICAgICAgIDExOCxcbiAgICAgICAgMTk2LFxuICAgICAgICAxMDEsXG4gICAgICAgIDE5OSxcbiAgICAgICAgMjQ4LFxuICAgICAgICAyNTEsXG4gICAgICAgIDU2LFxuICAgICAgICAyMixcbiAgICAgICAgNTgsXG4gICAgICAgIDEwMCxcbiAgICAgICAgMjMwLFxuICAgICAgICAyNixcbiAgICAgICAgMTU4LFxuICAgICAgICA1MyxcbiAgICAgICAgMTEyLFxuICAgICAgICA5OCxcbiAgICAgICAgMjM0LFxuICAgICAgICAxNjQsXG4gICAgICAgIDIzLFxuICAgICAgICAyMDksXG4gICAgICAgIDE1LFxuICAgICAgICAxMzRcbiAgICAgIF1cbiAgICB9LFxuICAgIFwia2V5SWRcIjogMVxuICB9LFxuICBcInJlZ2lzdHJhdGlvbklkXCI6IDI0OSxcbiAgXCJhZHZTZWNyZXRLZXlcIjogXCJKVmNEalFLL09raThZbGQ0WmxhMGJSNFMyRXByU3JzVTltRUphVDlaUnRBPVwiLFxuICBcInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlc1wiOiBbXSxcbiAgXCJuZXh0UHJlS2V5SWRcIjogMzEsXG4gIFwiZmlyc3RVbnVwbG9hZGVkUHJlS2V5SWRcIjogMzEsXG4gIFwiYWNjb3VudFN5bmNDb3VudGVyXCI6IDAsXG4gIFwiYWNjb3VudFNldHRpbmdzXCI6IHtcbiAgICBcInVuYXJjaGl2ZUNoYXRzXCI6IGZhbHNlXG4gIH0sXG4gIFwiZGV2aWNlSWRcIjogXCIxQTFQLTJXblFmT1NBaG5BUHlHVFR3XCIsXG4gIFwicGhvbmVJZFwiOiBcIjRkMjc1MWYyLWZiNTktNDJlZC1iZjYzLWQzOGY5YjkyMDVlNFwiLFxuICBcImlkZW50aXR5SWRcIjoge1xuICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgIFwiZGF0YVwiOiBbXG4gICAgICAxOTMsXG4gICAgICAyMjUsXG4gICAgICA0MSxcbiAgICAgIDU2LFxuICAgICAgMjQ0LFxuICAgICAgMTAxLFxuICAgICAgOCxcbiAgICAgIDExNyxcbiAgICAgIDEzNixcbiAgICAgIDI0NSxcbiAgICAgIDExNixcbiAgICAgIDU3LFxuICAgICAgOTUsXG4gICAgICAxOTUsXG4gICAgICA5MCxcbiAgICAgIDIxNCxcbiAgICAgIDMyLFxuICAgICAgMjM1LFxuICAgICAgNjIsXG4gICAgICAxNVxuICAgIF1cbiAgfSxcbiAgXCJyZWdpc3RlcmVkXCI6IHRydWUsXG4gIFwiYmFja3VwVG9rZW5cIjoge1xuICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgIFwiZGF0YVwiOiBbXG4gICAgICAxMTMsXG4gICAgICAxNTgsXG4gICAgICAyMzAsXG4gICAgICAyMTgsXG4gICAgICAxMyxcbiAgICAgIDg4LFxuICAgICAgMTIxLFxuICAgICAgNixcbiAgICAgIDYyLFxuICAgICAgMTA5LFxuICAgICAgMTYxLFxuICAgICAgODMsXG4gICAgICA5NSxcbiAgICAgIDI0NyxcbiAgICAgIDQsXG4gICAgICAxODAsXG4gICAgICAyMTcsXG4gICAgICAxMTAsXG4gICAgICAxMjYsXG4gICAgICA2MVxuICAgIF1cbiAgfSxcbiAgXCJyZWdpc3RyYXRpb25cIjoge30sXG4gIFwicGFpcmluZ0NvZGVcIjogXCJGQkRGUkVOOFwiLFxuICBcIm1lXCI6IHtcbiAgICBcImlkXCI6IFwiMjM0OTAyNTIyMDI4Nzo4QHMud2hhdHNhcHAubmV0XCIsXG4gICAgXCJsaWRcIjogXCIxODk1MjAwMjg5MDk1OTc6OEBsaWRcIlxuICB9LFxuICBcImFjY291bnRcIjoge1xuICAgIFwiZGV0YWlsc1wiOiBcIkNKaVZyc2dHRUxxMC9iUUdHQUlnQUNnQVwiLFxuICAgIFwiYWNjb3VudFNpZ25hdHVyZUtleVwiOiBcIk9EcUdjcTJad3NuZzI0ZndqV2NuOWdkTExRZnpHaEVUdXRHNzZadFFLeXc9XCIsXG4gICAgXCJhY2NvdW50U2lnbmF0dXJlXCI6IFwiMW53dlNpTkFiTWx4UUo2c0dvVjlxdU5HNFJ0YkpBdkVCOXhGTGovOUUzbUpzUFFKVFBvaVM3THhjRi9NcVM2cDNkMFNXbkkzVUJUNXYreElJYjZTRHc9PVwiLFxuICAgIFwiZGV2aWNlU2lnbmF0dXJlXCI6IFwiQXQzU0JMZkFQWUtqeCtOZnVpK1dlN24vdHFDcnVzSCtqNFh3S2JIY21JRTA5R2JSeGpyTms1U09KQStCZnhIMjlKYlNpWGtrOFZMSlR6TzJRY1VqaFE9PVwiXG4gIH0sXG4gIFwic2lnbmFsSWRlbnRpdGllc1wiOiBbXG4gICAge1xuICAgICAgXCJpZGVudGlmaWVyXCI6IHtcbiAgICAgICAgXCJuYW1lXCI6IFwiMjM0OTAyNTIyMDI4Nzo4QHMud2hhdHNhcHAubmV0XCIsXG4gICAgICAgIFwiZGV2aWNlSWRcIjogMFxuICAgICAgfSxcbiAgICAgIFwiaWRlbnRpZmllcktleVwiOiB7XG4gICAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgICBcImRhdGFcIjogW1xuICAgICAgICAgIDUsXG4gICAgICAgICAgNTYsXG4gICAgICAgICAgNTgsXG4gICAgICAgICAgMTM0LFxuICAgICAgICAgIDExNCxcbiAgICAgICAgICAxNzMsXG4gICAgICAgICAgMTUzLFxuICAgICAgICAgIDE5NCxcbiAgICAgICAgICAyMDEsXG4gICAgICAgICAgMjI0LFxuICAgICAgICAgIDIxOSxcbiAgICAgICAgICAxMzUsXG4gICAgICAgICAgMjQwLFxuICAgICAgICAgIDE0MSxcbiAgICAgICAgICAxMDMsXG4gICAgICAgICAgMzksXG4gICAgICAgICAgMjQ2LFxuICAgICAgICAgIDcsXG4gICAgICAgICAgNzUsXG4gICAgICAgICAgNDUsXG4gICAgICAgICAgNyxcbiAgICAgICAgICAyNDMsXG4gICAgICAgICAgMjYsXG4gICAgICAgICAgMTcsXG4gICAgICAgICAgMTksXG4gICAgICAgICAgMTg2LFxuICAgICAgICAgIDIwOSxcbiAgICAgICAgICAxODcsXG4gICAgICAgICAgMjMzLFxuICAgICAgICAgIDE1NSxcbiAgICAgICAgICA4MCxcbiAgICAgICAgICA0MyxcbiAgICAgICAgICA0NFxuICAgICAgICBdXG4gICAgICB9XG4gICAgfVxuICBdLFxuICBcInBsYXRmb3JtXCI6IFwiYW5kcm9pZFwiLFxuICBcImxhc3RBY2NvdW50U3luY1RpbWVzdGFtcFwiOiAxNzIxNzE5MzU3XG59IiwKICAiYXBwLXN0YXRlLXN5bmMta2V5LXVuZGVmaW5lZC5qc29uIjoge30KfQ==", //Enter Your Session Id Here
  //_________________________________________________________________________________________________________________________________
  SUDO: process.env.SUDO || "2349025220287",
  //_________________________________________________________________________________________________________________________________
  SPAM_COUNT: process.env.SPAM_COUNT || "10",
  //_________________________________________________________________________________________________________________________________
  LANG: process.env.LANG || "EN",
  //_________________________________________________________________________________________________________________________________
  LOGS: toBool(process.env.LOGS) || true,
  //_________________________________________________________________________________________________________________________________
  MENTION_DATA: process.env.MENTION_DATA || "01:43 ━━━●───── 03:50;⇆ㅤ ||◁ㅤ❚❚ㅤ▷||ㅤ ⇆;919074692450;https://graph.org/file/63942461d4b8d78b360d3.jpg",
  //_________________________________________________________________________________________________________________________________
  MENTION_AUDIO: process.env.MENTION_AUDIO || "https://i.imgur.com/NCifJWe.mp4;https://graph.org/file/ecf0772cb95111796848c.mp4",
  //_________________________________________________________________________________________________________________________________
  MENTION: process.env.MENTION || 'false',
  //_________________________________________________________________________________________________________________________________
  HANDLERS: process.env.PREFIX || '.',
  //_________________________________________________________________________________________________________________________________
  RMBG_KEY: process.env.RMBG_KEY || false,
  //_________________________________________________________________________________________________________________________________
  STICKER_DATA: "🎯𝙿𝚑𝚘𝚎𝚗𝚒𝚡-𝙼𝙳;𝙰𝚋𝚑𝚒𝚜𝚑𝚎𝚔 𝚂𝚞𝚛𝚎𝚜𝚑☘️",
  //_________________________________________________________________________________________________________________________________
  WELCOME_MSG: process.env.WELCOME_MSG || "👋 Hello *@user* Welcome To Our Group *@gname*\n*Total Members:* @count\n*Group Description:*\n@gdesc {pp}",
  //_________________________________________________________________________________________________________________________________
  GOODBYE_MSG: process.env.GOODBYE_MSG || "👋 GoodBye *@user* From *@gname*\n*Total Members:* @count {pp}",
  //_________________________________________________________________________________________________________________________________
  DATABASE_URL: DATABASE_URL,
  //_________________________________________________________________________________________________________________________________
  HEROKU_APP_NAME: process.env.HEROKU_APP_NAME || " ",
  //_________________________________________________________________________________________________________________________________
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || " ",
  //_________________________________________________________________________________________________________________________________
  OWNER_NAME: process.env.OWNER_NAME || "Abhishek Suresh",
  //_________________________________________________________________________________________________________________________________
  OWNER_NUMBER: process.env.OWNER_NUMBER || "918157993101",
  //_________________________________________________________________________________________________________________________________
  BOT_NAME: process.env.BOT_NAME || "Phoenix-MD",
  //_________________________________________________________________________________________________________________________________
  WORK_TYPE: process.env.MODE || "public",
  //_________________________________________________________________________________________________________________________________
  BASE_URL: "https://abhi-appi-9a0e16f0ca75.herokuapp.com/",
  //_________________________________________________________________________________________________________________________________
  //Database
  DATABASE:
    DATABASE_URL === "./lib/database.db"
      ? new Sequelize({
          dialect: "sqlite",
          storage: DATABASE_URL,
          logging: false,
        })
      : new Sequelize(DATABASE_URL, {
          dialect: "postgres",
          ssl: true,
          protocol: "postgres",
          dialectOptions: {
            native: true,
            ssl: { require: true, rejectUnauthorized: false },
          },
          logging: false,
        }),
};
